version: '3'
services:
  app: &base
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file: docker/.env
    container_name: app
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    ports:
      - 3000:3000
    depends_on:
      - db
      # - redis
    tty: true
    stdin_open: true
    command: bin/rails s -p 3000 -b '0.0.0.0'

  db:
    build:
      context: .
      dockerfile: docker/postgresql/Dockerfile
    env_file: docker/.env
    container_name: postgres
    volumes:
      - db-data:/var/lib/postgres
    ports:
      - 5432:5432

  # db:
  #   image: mysql:5.7.23
  #   env_file: docker/.env
  #   container_name: mysql
  #   volumes:
  #     - ./docker/mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
  #     - db-data:/var/lib/mysql
  #   ports:
  #     - 3306:3306

  # redis:
  #   image: redis:3.2.9-alpine
  #   env_file: docker/.env
  #   container_name: redis
  #   volumes:
  #     - redis-data:/data
  #   ports:
  #     - 6379:6379

volumes:
  bundle:
  db-data:
  redis-data:
